
title: Forward Propagation

description: >
  Forward Propagation is a simple tool for looking at recent human
  history in terms of generations instead of years.

markdown: kramdown

exclude: [
    "node_modules",
    "design",
    "src"
]